Active users on top
googleinterns/step257-2020 pull request #128
Opened 2020-09-24 13:18 UTC by AndrzejPodo

2020-09-24 13:30 UTC, PaulKovalov commented on sticknotes-frontend/src/app/user-list/user-list.component.ts
> +      this.activeUsers = this.usersWithRole.filter(user => this.activeUsersIdSet.has(+user.id));
I think its better to use `Number()` to convert string to number

2020-09-24 13:32 UTC, AndrzejPodo commented
@googlebot I consent.

2020-09-24 13:36 UTC, AndrzejPodo commented on sticknotes-frontend/src/app/user-list/user-list.component.ts
> +      this.activeUsers = this.usersWithRole.filter(user => this.activeUsersIdSet.has(+user.id));
why, because of readability or is there any other reason?

2020-09-24 15:03 UTC, PaulKovalov commented on sticknotes-frontend/src/app/user-list/user-list.component.ts
> +      this.activeUsers = this.usersWithRole.filter(user => this.activeUsersIdSet.has(+user.id));
yes, basically adding + is JavaScript-ish way to convert string to number, but here we use Typescript, and it has more fancy mechanisms

2020-09-24 15:06 UTC, PaulKovalov commented
@AndrzejPodo I've changed base branch there and back to help github recalculate diff

2020-09-24 15:07 UTC, PaulKovalov commented on sticknotes-frontend/src/app/user-list/user-list.component.html
> +      <mat-list-item *ngFor="let userWithRole of inactiveUsers" (click)="openEditUserDialog(userWithRole)"
Active users will be shown in a separate tab?

2020-09-24 15:08 UTC, PaulKovalov commented on sticknotes-frontend/src/app/user-list/user-list.component.html
> +      </mat-list-item>
all this is duplicated code right?

2020-09-24 15:21 UTC, AndrzejPodo commented on sticknotes-frontend/src/app/user-list/user-list.component.html
> +      <mat-list-item *ngFor="let userWithRole of inactiveUsers" (click)="openEditUserDialog(userWithRole)"
No.

2020-09-24 15:21 UTC, AndrzejPodo commented on sticknotes-frontend/src/app/user-list/user-list.component.html
> +      </mat-list-item>
Yes.

2020-09-24 15:22 UTC, AndrzejPodo commented on sticknotes-frontend/src/app/user-list/user-list.component.html
> +      </mat-list-item>
We can build component for that, but don't you think it's a bit not necessary?

2020-09-24 15:22 UTC, AndrzejPodo commented on sticknotes-frontend/src/app/user-list/user-list.component.html
> +      <mat-list-item *ngFor="let userWithRole of inactiveUsers" (click)="openEditUserDialog(userWithRole)"
List of active users are simply above inactive, this are disjointed sets, right?

2020-09-24 15:25 UTC, AndrzejPodo commented on sticknotes-frontend/src/app/user-list/user-list.component.ts
> +      this.activeUsers = this.usersWithRole.filter(user => this.activeUsersIdSet.has(+user.id));
Afaik + and Numer() work the same way in terms of input/output, so unary plus operator should be fine. If you really insist we can change it, but imo + looks better as it gives less code.

2020-09-24 15:28 UTC, AndrzejPodo commented on sticknotes-frontend/src/app/user-list/user-list.component.html
> +      </mat-list-item>
Btw. I don't know why, but before this solution I was just sorting users using custom comparator, but changes is order haven't reflected in the UI.

2020-09-24 15:54 UTC, PaulKovalov commented on sticknotes-frontend/src/app/user-list/user-list.component.html
> +      </mat-list-item>
I think it is not the case of "unnecessary code".

2020-09-24 15:56 UTC, PaulKovalov commented on sticknotes-frontend/src/app/user-list/user-list.component.html
> +      </mat-list-item>
Actually sorting is what I wanted to advise. I think we can make it work with custom comparator

2020-09-24 15:56 UTC, PaulKovalov commented on sticknotes-frontend/src/app/user-list/user-list.component.ts
> +      this.activeUsers = this.usersWithRole.filter(user => this.activeUsersIdSet.has(+user.id));
I think it is not the case of "unnecessary code".

2020-09-24 16:04 UTC, AndrzejPodo commented on sticknotes-frontend/src/app/user-list/user-list.component.html
> +      </mat-list-item>
I make it using custom comparator but changes in sorting haven't reflected in UI

2020-09-24 16:05 UTC, PaulKovalov commented on sticknotes-frontend/src/app/user-list/user-list.component.html
> +      </mat-list-item>
Can you implement this solution please? We'll debug it

2020-09-24 16:09 UTC, AndrzejPodo commented on sticknotes-frontend/src/app/user-list/user-list.component.ts
> +      this.activeUsers = this.usersWithRole.filter(user => this.activeUsersIdSet.has(+user.id));
ok i can change to Number() :D

2020-09-24 16:11 UTC, PaulKovalov commented on sticknotes-frontend/src/app/user-list/user-list.component.ts
> +      this.activeUsers = this.usersWithRole.filter(user => this.activeUsersIdSet.has(+user.id));
thanks!

2020-09-24 16:41 UTC, PaulKovalov commented on sticknotes-frontend/src/app/user-list/user-list.component.ts
> +      if(a.role === UserRole.OWNER || (activeIdSet.has(+a.id) && !activeIdSet.has(Number(b.id)))){
Looks like you decided to mix + with Number :D

2020-09-24 17:07 UTC, AndrzejPodo commented on sticknotes-frontend/src/app/user-list/user-list.component.ts
> +      if(a.role === UserRole.OWNER || (activeIdSet.has(+a.id) && !activeIdSet.has(Number(b.id)))){
Omg, I haven't noticed that xdd

2020-09-25 09:38 UTC, PaulKovalov requested changes

2020-09-25 09:38 UTC, PaulKovalov commented on sticknotes-frontend/src/app/user-list/user-list.component.ts
> +  public inactiveUsers: UserBoardRole[] = [];
this is not used

2020-09-25 09:46 UTC, PaulKovalov approved these changes

2020-09-25 11:15 UTC, merged