Servlet/board users list
googleinterns/step257-2020 pull request #45
Opened 2020-08-25 10:20 UTC by AndrzejPodo

- fix problems with tests by clearing objectify cache
- doGet to retrieving board users list finished and tested 
- doPost for adding users with role to board finished and tested
- doDelete for deleting users from board finished and tested

2020-08-25 10:45 UTC, PaulKovalov commented
@googlebot I consent.

2020-08-25 10:52 UTC, PaulKovalov requested changes

2020-08-25 10:52 UTC, PaulKovalov commented on sticknotesbackend/src/main/java/com/google/sticknotesbackend/servlets/UserListServlet.java
> +    UserBoardRole datastoreData = ofy().load().type(UserBoardRole.class).filter("board", board).filter("user", user)
pls rename to `role` or smth more descriptive than just `datastoreData`

2020-08-25 10:52 UTC, PaulKovalov commented on sticknotesbackend/src/main/java/com/google/sticknotesbackend/servlets/UserListServlet.java
> +      response.getWriter().println("User already in the list.");
I guess there is already a method `badRequest` in abstract base servlet class, you can use it

2020-08-25 10:52 UTC, PaulKovalov commented on sticknotesbackend/src/main/java/com/google/sticknotesbackend/servlets/UserListServlet.java
> +      response.getWriter().println("Error while reading request param.");
same about `badRequest`

2020-08-25 10:52 UTC, PaulKovalov commented on sticknotesbackend/src/test/java/com/google/sticknotesbackend/servlets/NotesboardTestBase.java
> +  }
It is availabe in your servlet, please remove it from here

2020-08-25 10:52 UTC, PaulKovalov commented on sticknotesbackend/src/test/java/com/google/sticknotesbackend/servlets/NotesboardTestBase.java
> +  }
`ofy().clear()` is not enough?

2020-08-25 10:52 UTC, PaulKovalov commented on sticknotesbackend/src/test/java/com/google/sticknotesbackend/servlets/UserListServletTest.java
>    }
Simply remove it from here, base class has this `@After` annotation and is calling the method

2020-08-25 10:52 UTC, PaulKovalov commented on sticknotesbackend/src/test/java/com/google/sticknotesbackend/servlets/UserListServletTest.java
> +    when(mockRequest.getParameter("id")).thenReturn(board2.id.toString());
Good!

2020-08-25 10:52 UTC, PaulKovalov commented on sticknotesbackend/src/test/java/com/google/sticknotesbackend/servlets/UserListServletTest.java
> +    Gson gson = getBoardGsonParser();
Here you can access this method from servlet

2020-08-25 11:05 UTC, AndrzejPodo commented on sticknotesbackend/src/test/java/com/google/sticknotesbackend/servlets/NotesboardTestBase.java
> +  }
what you mean?

2020-08-25 11:08 UTC, PaulKovalov commented on sticknotesbackend/src/test/java/com/google/sticknotesbackend/servlets/NotesboardTestBase.java
> +  }
why do you need this if you clearing the cache? Isn't clearing cache enough to make tests work?

2020-08-25 11:16 UTC, AndrzejPodo commented on sticknotesbackend/src/main/java/com/google/sticknotesbackend/servlets/UserListServlet.java
> +      response.getWriter().println("User already in the list.");
oh yes, i didn't notice it, thanks.

2020-08-25 11:36 UTC, PaulKovalov requested changes

2020-08-25 11:36 UTC, PaulKovalov commented on sticknotesbackend/src/main/java/com/google/sticknotesbackend/servlets/UserListServlet.java
> +    }
You can simplify this code as follows:
```String boardRoleIdParam = request.getParameter("id");
if (boardRoleIdParam == null) {
   badRequest("Error while reading request param.", response);
}
Long boardRoleId = Long.parseLong(boardRoleIdParam);
```
It doesn't throw any exception, IMO looks better without try catch

2020-08-25 11:36 UTC, AndrzejPodo commented on sticknotesbackend/src/test/java/com/google/sticknotesbackend/servlets/NotesboardTestBase.java
> +  }
This is not connected to the problems with tests. I write this because I think it's useful to ensure datastore is in clear state before each test. I have some tests that are adding or removing entities and changing overall state of datastore, and also your tests are interacting with datastore.

2020-08-25 11:40 UTC, AndrzejPodo commented on sticknotesbackend/src/test/java/com/google/sticknotesbackend/servlets/NotesboardTestBase.java
> +  }
I'm just not sure if this datastore helper is reliable. I can't manually send /rest request to datastore, and that's what exactly datastore helper is trying to do, so I was just not sure if it really resets datastore. And additionally reset() dont work with datastore emulator started without --no-store-on-disk which is bad.

2020-08-25 11:42 UTC, PaulKovalov commented on sticknotesbackend/src/test/java/com/google/sticknotesbackend/servlets/NotesboardTestBase.java
> +  }
wait, what `/reset` does than? Remeber you added this
`protected final LocalDatastoreHelper datastoreHelper = LocalDatastoreHelper.create(8484);`
to clear datastore between tests

2020-08-25 11:42 UTC, AndrzejPodo commented on sticknotesbackend/src/main/java/com/google/sticknotesbackend/servlets/UserListServlet.java
> +    }
wait... but what if someone pass for example "board21" as id? `

2020-08-25 11:43 UTC, PaulKovalov requested changes

2020-08-25 11:43 UTC, PaulKovalov commented on sticknotesbackend/src/test/java/com/google/sticknotesbackend/servlets/NotesboardTestBase.java
> +  }
okay, in this case remove this `protected final LocalDatastoreHelper datastoreHelper = LocalDatastoreHelper.create(8484)`

2020-08-25 11:44 UTC, PaulKovalov commented on sticknotesbackend/src/main/java/com/google/sticknotesbackend/servlets/UserListServlet.java
> +    }
we are not exposing our APIs, our client will not pass invalid data i guess

2020-08-25 11:50 UTC, PaulKovalov commented on sticknotesbackend/src/main/java/com/google/sticknotesbackend/servlets/UserListServlet.java
> +    }
If you want to have this check, okay, let it be. I just think it is not required

2020-08-25 11:59 UTC, PaulKovalov requested changes

2020-08-25 11:59 UTC, PaulKovalov commented on sticknotesbackend/src/main/java/com/google/sticknotesbackend/servlets/UserListServlet.java
> +      return;
Else is not needed right? And return in the end as well

2020-08-25 11:59 UTC, PaulKovalov commented on sticknotesbackend/src/main/java/com/google/sticknotesbackend/servlets/UserListServlet.java
>      return;
You can leave this ofc, just want to note that `return`s from void methods in the ends doesn't make much sense

2020-08-25 11:59 UTC, PaulKovalov commented on sticknotesbackend/src/test/java/com/google/sticknotesbackend/servlets/NotesboardTestBase.java
> +*/
Smth bad happened to the comment indent

2020-08-25 11:59 UTC, PaulKovalov commented on sticknotesbackend/src/test/java/com/google/sticknotesbackend/servlets/UserListServletTest.java
> +    UserBoardRole datastoreData = ofy().load().type(UserBoardRole.class).filter("board", board2).filter("user", user1)
bad name here as well

2020-08-25 11:59 UTC, PaulKovalov commented on sticknotesbackend/src/test/java/com/google/sticknotesbackend/servlets/UserListServletTest.java
> +    UserBoardRole datastoreData = ofy().load().type(UserBoardRole.class).id(userBoardRole1.id).now();
and here bad name as well

2020-08-25 12:12 UTC, AndrzejPodo commented on sticknotesbackend/src/main/java/com/google/sticknotesbackend/servlets/UserListServlet.java
>      return;
Yes I'm aware of that 👍

2020-08-26 11:21 UTC, PaulKovalov approved these changes

2020-08-26 11:28 UTC, merged