Servlet/authentication
googleinterns/step257-2020 pull request #52
Opened 2020-08-26 13:41 UTC by AndrzejPodo

Adds:
-servlet for obtaining User details
-servlet for obtaining Login Url
-servlet for obtaining Logout Url

2020-08-26 13:51 UTC, PaulKovalov commented
@googlebot I consent.

2020-08-26 15:42 UTC, PaulKovalov requested changes

2020-08-26 15:42 UTC, PaulKovalov commented on sticknotes-frontend/src/app/login-page/login-page.component.ts
> +}
broken indent

2020-08-26 15:42 UTC, PaulKovalov commented on sticknotes-frontend/src/app/login-page/login-page.component.ts
> +    console.log(this.loginUrl);
debug log

2020-08-26 15:42 UTC, PaulKovalov commented on sticknotes-frontend/src/app/services/user.service.ts
> +      return this.userSubject.value;
why here you return `.value`, and in `catchError` clause you return `.asObservable()`?

2020-08-27 08:53 UTC, AndrzejPodo commented on sticknotes-frontend/src/app/services/user.service.ts
> +      return this.userSubject.value;
because it's the expected way
![image](https://user-images.githubusercontent.com/27630111/91419126-54bfb180-e853-11ea-962e-ea47f2b2dc1c.png)
but I figured out catching error here is not needed.

2020-08-27 09:29 UTC, PaulKovalov approved these changes

2020-08-27 09:30 UTC, merged